# Generated by Django 5.2.5 on 2025-09-03 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_saver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='url',
            new_name='audio',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='description',
            new_name='text',
        ),
    ]
