# Generated by Django 5.2.5 on 2025-09-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_saver', '0003_playlist_is_public_alter_comment_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music_saver.song'),
        ),
    ]
