# Generated by Django 5.2.5 on 2025-09-05 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_saver', '0004_playlist_views_song_views_alter_playlist_is_public_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(choices=[('pop', 'Pop'), ('rock', 'Rock'), ('hiphop', 'Hip-Hop'), ('electronic', 'Electronic'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, choices=[('C', 'C Major'), ('Cm', 'C Minor'), ('D', 'D Major'), ('Dm', 'D Minor'), ('E', 'E Major'), ('Em', 'E Minor'), ('F', 'F Major'), ('Fm', 'F Minor'), ('G', 'G Major'), ('Gm', 'G Minor'), ('A', 'A Major'), ('Am', 'A Minor'), ('B', 'B Major'), ('Bm', 'B Minor')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
