# Generated by Django 5.2.5 on 2025-09-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_saver', '0005_song_bpm_song_genre_song_key_song_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
