# Generated by Django 5.2.5 on 2025-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_saver', '0006_alter_song_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='author',
            field=models.CharField(default='Ziferblat', max_length=20),
            preserve_default=False,
        ),
    ]
