# Generated by Django 5.2.5 on 2025-09-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_saver', '0007_song_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
